---
version: 2.1

# Prevent all circleci deployment to Cloudsmith change parameters: > deploy > default to false
# Prevent all travis and appveyor deployment to Cloudsmith change those yml files.
# Prevent all circleci builds from building change parameters > run_workflow_build > default to false
# Enable all builds parameters: > run_workflow_buid: > default: true   AND put 
# Then to enable a certain circleci build only, change the parameter at the top to "false" and localy under workflow to "true".
# IE: workflows: > version: 2 > build_all: > jobs: > - build-armhf-stretch: > build: > when: << pipeline.parameters.run_workflow_build >>
# Changed to: workflows: > version: 2 > build_all: > jobs: > - build-armhf-stretch: > build: > when: true
# and in Workflow section always use    build:  >  when: << pipeline.parameters.run_workflow_build >>

#  build-armhf-stretch:
#    machine: true
#    environment:
#      - OCPN_TARGET=stretch-armhf
#      - DOCKER_IMAGE=jongough/raspbian-stretch:latest
#      - BUILD_FLAGS=-j3
#      - BUILD_ENV=raspbian
#    steps:
#      - checkout
#      - when:
#          condition: << pipeline.parameters.run_workflow_build >>
#          steps:
#            - run: chmod a+x ./ci/*.sh
#            - run:
#               command: ci/circleci-build-raspbian-armhf.sh
#               no_output_timeout: 30m
#            - when:
#              condition: << pipeline.parameters.deploy >>
#              steps:
#                - run: ci/cloudsmith-upload.sh
#                - run: echo "deploying"

parameters:
  run_workflow_build:
    type: boolean
    default: false
  run_workflow_deploy:
    type: boolean
    default: false

jobs:
    build-armhf-stretch:
        machine: true
        environment:
        - OCPN_TARGET=stretch-armhf
        - DOCKER_IMAGE=jongough/raspbian-stretch:latest
        - BUILD_FLAGS=-j3
        - BUILD_ENV=raspbian
          - when:
            condition: << pipeline.parameters.run_workflow_build >>
            steps:
            - checkout
            - run: chmod a+x ./ci/*.sh
            - run:
                command: ci/circleci-build-raspbian-armhf.sh
                no_output_timeout: 30m
            - when:
                condition: <<pipeline.parameters.run_workflow_deploy>>
                steps:
                  - run: ci/cloudsmith-upload.sh
                  - run: echo "deploying"
    build-armhf-buster:
        machine: true
        environment:
        - OCPN_TARGET=buster-armhf
        - DOCKER_IMAGE=jongough/raspbian-buster:plugin_build_tooling_current
        - BUILD_FLAGS=-j3
        - BUILD_ENV=raspbian
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - when:
            condition: <<pipeline.parameters.run_workflow_deploy>>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-armhf-bionic-64:
        machine: true
        environment:
        - OCPN_TARGET=bionic-arm64
        - OCPN_BRANCH=master
        - DOCKER_IMAGE=arm64v8/ubuntu:18.04
        - BUILD_FLAGS=-j3
        - BUILD_ENV=ubuntu
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-trusty:
        docker:
        - image: circleci/buildpack-deps:trusty-scm
        environment:
        - OCPN_TARGET:  trusty
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ trusty main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-trusty.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"		
    build-xenial:
        docker:
        - image: circleci/buildpack-deps:xenial-scm
        environment:
        - OCPN_TARGET:  xenial
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"		
    build-bionic:
        docker:
        - image: circleci/buildpack-deps:bionic-scm
        environment:
        - OCPN_TARGET:  bionic
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"		
    build-bionic-gtk3:
        docker:
        - image: circleci/buildpack-deps:bionic-scm
        environment:
        - BUILD_GTK3: true
        - OCPN_TARGET:  bionic-gtk3
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-focal:
        docker:
        - image: circleci/buildpack-deps:focal-scm
        environment:
        - OCPN_TARGET:  focal
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-focal-gtk3:
        docker:
        - image: circleci/buildpack-deps:focal-scm
        environment:
        - BUILD_GTK3: true
        - OCPN_TARGET: focal-gtk3
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-buster:
        docker:
        - image: circleci/buildpack-deps:buster-scm
        environment:
        - OCPN_TARGET:  buster
        steps:
        - checkout
        - run: >
            echo "deb-src http://ftp.us.debian.org/debian buster main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://ftp.us.debian.org/debian buster-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-flatpak:
        machine:
            image: circleci/classic:201808-01
        environment:
        - OCPN_TARGET:  flatpak
        - CLOUDSMITH_PKG_EXT: gz
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-flatpak.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-fedora:
        docker:
        - image: fedora:29
        environment:
        - OCPN_TARGET:  fedora
        steps:
        - run: su -c "dnf install -q -y git openssh-clients openssh-server"
        - checkout
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-fedora.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"		
    build-mingw:
        docker:
        - image: fedora:29
        environment:
        - OCPN_TARGET:  mingw
        - CLOUDSMITH_PKG_EXT: exe
        steps:
        - run: su -c "dnf install -q -y git openssh-clients openssh-server"
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-mingw.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-macos:
        macos:
            xcode: "10.0.0"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-android-arm64:
        docker:
        - image: circleci/android:api-28-ndk 
        environment:
        - OCPN_TARGET:  android-arm64
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-android-arm64.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"
    build-android-armhf:
        docker:
        - image: circleci/android:api-28-ndk 
        environment:
        - OCPN_TARGET:  android-armhf
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-android-armhf.sh
        - when:
            condition: << pipeline.parameters.run_workflow_deploy >>
            steps:
              - run: ci/cloudsmith-upload.sh
              - run: echo "deploying"

workflows:
    version: 2
    build_all:
        jobs:
        - build-armhf-stretch:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-armhf-buster:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
# Currently circleci does not build armf64 correctly due to no suitable docker image
#        - build-armhf-bionic-64:
#            filters:
#                branches:
#                    ignore:
#                    - devel
#                    - tmp
#                tags:
#                    only: /.*/
        - build-trusty:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-xenial:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-bionic:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-bionic-gtk3:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
# there is no focal gtk2 available so this will not be built
#        - build-focal:
#            filters:
#                branches:
#                    ignore:
#                    - devel
#                    - tmp
#                tags:
#                    only: /.*/
        - build-focal-gtk3:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-buster:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-flatpak:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
# Fedora is being removed from the supplied list of environments so don't build
#        - build-fedora:
#            filters:
#                branches:
#                    ignore:
#                    - devel
#                    - tmp
#                tags:
#                    only: /.*/
        - build-mingw:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-macos:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
# GPS Odometer is currently not supporting Android
#        - build-android-arm64:
#            filters:
#                branches:
#                    ignore:
#                    - devel
#                    - tmp
#                tags:
#                    only: /.*/
#        - build-android-armhf:
#            filters:
#                branches:
#                    ignore:
#                    - devel
#                    - tmp
#                tags:
#                    only: /.*/
